export default function api() {
  const devApiDomain = process.env.NEXT_PUBLIC_DEV_API_DOMAIN;

  return {
    "sign-up": `${devApiDomain}api/user/`,
    "log-in": `${devApiDomain}api/user/login/`,
    "log-out": `${devApiDomain}api/user/logout/`,
    "patch-profile": `${devApiDomain}api/user/`,
    nationality: `${devApiDomain}api/location/nationality/`,
    country: `${devApiDomain}api/location/country/`,
    city: `${devApiDomain}api/location/city/`,
    currency: `${devApiDomain}api/currency/`,
    "currency-pair": `${devApiDomain}api/currency-pair/`,
    wallet: `${devApiDomain}api/wallet/`,
    "wallet-asset": `${devApiDomain}api/wallet-asset/`,
    "wallet-tank": `${devApiDomain}api/wallet-tank/`,
    "wallet-tank-type": `${devApiDomain}api/wallet-tank-type/`,
    branch: `${devApiDomain}api/branch/`,
    deposit: `${devApiDomain}api/order/deposit/`,
    withdrawal: `${devApiDomain}api/order/withdrawal/`,
    transfer: `${devApiDomain}api/order/transfer/`,
    exchange: `${devApiDomain}api/order/exchange/`,
    "pending-requests": `${devApiDomain}api/wallet-pending-request/`,
    "watch-list": `${devApiDomain}api/index/watch-list/`,
    "table-exchange": `${devApiDomain}api/index/table-exchange/`,
    "pending-exchange": `${devApiDomain}api/index/pending-exchange/`,
    status: `${devApiDomain}api/status/`,
    "other-exchanges-rate": `${devApiDomain}api/exchange-rate/`,
    locale: `${devApiDomain}api/locale/`,
    "check-email": `${devApiDomain}api/user/forget-password-check/`,
    "send-email": `http://api.emailjs.com/api/v1.0/email/send`,
    "forgot-password": `${devApiDomain}api/user/forget-password-set/`,
    "top-5-report": `${devApiDomain}api/report/`,
    "change-password": `${devApiDomain}api/user/change-password/`,
    "support-location": `${devApiDomain}api/location-supports/support_locations/`,
  };
}
